#spring:
#  datasource:
#    password: 1234
#    url: jdbc:postgresql://localhost:5432/spring_security_examples
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create
spring:
  application:
    name: postgres
  datasource:
    url: jdbc:postgresql://localhost:5433/accounting
    username: postgres
    password: NeronKid
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855